
php:
  build: .
  ports:
   - "8080:80"
   - "1443:443"
  volumes:
   - ./www:/var/www/html
  links:
   - db
db:
  image: mysql:5.7
  ports:
   - "13306:3306"
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=bytes
   - MYSQL_DATABASE=byteslivres